{'config': {'name': 'bluedartstack', 'platform': 'tensorrt_plan', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 32, 'input': [{'name': 'input_1', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NCHW', 'dims': ['3', '384', '1248']}], 'output': [{'name': 'output_bbox/BiasAdd', 'data_type': 'TYPE_FP32', 'dims': ['20', '24', '78']}, {'name': 'output_cov/Sigmoid', 'data_type': 'TYPE_FP32', 'dims': ['5', '24', '78']}], 'instance_group': [{'name': 'bluedartstack', 'count': 1, 'gpus': [0], 'kind': 'KIND_GPU'}], 'default_model_filename': 'model.plan', 'dynamic_batching': {'preferred_batch_size': [32]}, 'optimization': {'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}}, 'backend': 'tensorrt'}}